# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Exercise1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Exercise1
  pod 'RxSwift'
  pod 'RxCocoa' 
  pod 'RxOptional'
  pod 'RxDataSources'

end
